### ISSUE TITLE
Verion 1 needs a Read Me file

### ISSUE THREAD

**Issue by turtlelovesshoes** [turtleloveshoes/SumoOnboarding#5]
The read me file should include: 

- The names of the custom components and their corresponding files 

- quilt names 

- Custom Page names

- css files added and how they are installed in Lithium. 

Version 1
Features included in Version One were Getting the Get involved page content live and accessible to all users, providing clear instructions and steps to get started contributing. 

Bugs and Version 2 plan

**Comment by cpswsg** [comment]
Fix it in commits: 05ff91d, 1354a24, b03c23c and 541d5b5
